### ISSUE TITLE
Reins of the Spotted Nightsaber

### ISSUE THREAD

**Issue by Phatcat** [classicdb/database#905]
Transforms you into a spotted panther instead of mounting up on a spotted nightsaber.

**Comment by Jaypy** [comment]
From what I could gather about this, the mount model ID is 6447. Oddly enough.(http://www.wowhead.com/item=8628/reins-of-the-spotted-nightsaber#screenshots:id=71140)

I guess that all mount spells takes the model of the mount from an existing NPC and for this mount its 7689. Change that npc's model to the one mentioned above and it should fix this.

This is what I wrote up (also corrects the spotted frostsaber item quality. just noticed it.):
`UPDATE item_template SET Quality = 3 WHERE entry = 8632;
UPDATE creature_template SET ModelId1 = 6447 WHERE Entry = 7689;`

**Comment by Phatcat** [comment]
I think you possibly misunderstood me; the item does NOT mount you up, it polymorphs you, this is not a matter of wrong model, this is a matter of wrong spell / wrong spell behaviour, this is why it has been slapped with the non-functional as well as the spell tags - that could have changed since I tested it, which was quite a while before I reported it, but I don't see how it would have changed without a db update on the item.

**Comment by Jaypy** [comment]
I don't know why, but the proposal I made, actually fixes the issue (atleast for me). I don't know exactly how models are structured and admit that i sort of stumbled upon the fix. But i guess the item aura, of mounting, can only work if the model has some sort of attribute that makes it a mount (my guess is dedicated mount rig bone) otherwise it just polymorphs ya.

Here's some quick proof. https://gyazo.com/9281d200fb649f2f47f4b8228bea9ba9

Edit: I fucked with the item displayID myself. Dont pay attention to that :p

**Comment by cala** [comment]
My first guess was to look at the spell DBC but it uses the exact same auras/effects than the similar spells.
So, I looked at the creature entry the spell used as the mount parameter and again, I found nothing different from other mounts.

So, Jaypy is probably right on what is going on and the logic of his fix seems correct. However, I can't tell if the model used is the one supposed to be used.

**Comment by Phatcat** [comment]
According to wowhead it is; http://www.wowhead.com/item=8628/reins-of-the-spotted-nightsaber

also when looking directly at the spell, it still shows this model (at wowhead); http://www.wowhead.com/spell=10792/spotted-panther ?

Edit*: one more link for the beast summoned; http://www.wowhead.com/npc=7689/spotted-nightsaber

**Comment by Phatcat** [comment]
Blizzard is bad at naming stuff, I was sure the nightsabers were the black ones, oh well.

**Comment by cala** [comment]
They are indeed not very good at naming some stuff, also remember that this is an alpha item made for testing purpose.

Closed by https://github.com/cmangos/classic-db/commit/4746f2704b151806b904c9632ccce75af7295ac7
Thank you.
